# Generated by Django 3.2.3 on 2021-06-16 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motivo',
            name='idMotivo',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Motivo'),
        ),
    ]
