# Generated by Django 3.2.3 on 2021-06-20 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_usuario_nickusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='NickUsuario',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Nick de Usuario'),
        ),
    ]
