# Generated by Django 3.2.3 on 2021-06-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_motivo_idmotivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='NickUsuario',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Nick der Usuario'),
        ),
    ]
