# Generated by Django 3.2.3 on 2021-06-16 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motivo',
            fields=[
                ('idMotivo', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Id de Motivo')),
                ('nombreMotivo', models.CharField(max_length=50, verbose_name='Nombre de Motivo')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('NickUsuario', models.IntegerField(max_length=30, primary_key=True, serialize=False, verbose_name='Nick der Usuario')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('email', models.CharField(max_length=70, verbose_name='Mail')),
                ('mensaje', models.CharField(max_length=200, verbose_name='Mensaje')),
                ('idMotivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.motivo')),
            ],
        ),
    ]
